apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: knotree-accounts-api
  namespace: knotree-accounts
  labels:
    app.kubernetes.io/name: knotree-accounts
    app.kubernetes.io/part-of: knotree-accounts
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: knotree-accounts
      app.kubernetes.io/component: api
